name: Deploy exposures to cti-qa

on:
  push:
    branches:
      - export-file-version

jobs:
  deploy-cti:
    name: Deploy to CTI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'

    - name: Install app dependencies
      run: npm install

    - name: Package lambdas
      run: |
        npm run artifact:create
      env:
        ORG: managed
        BUILD: 0.0.1

    - name: Deploy exposures
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.CTI_QA_KEY }}
        aws_secret_access_key: ${{ secrets.CTI_QA_SECRET }}
        aws_region: eu-west-1
        function_name: qa-fight-together-exposures
        zip_file: lambdas.zip
